# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Please check docs/dependencies.md for ignore entries

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/aws/lambda/cloud-front-s3-logs-reorganizer"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/aws/lambda/cloud-front-storefront-redirect-to-trailing-slash"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/aws/lambda/cloud-front-storefront-rewrite-index-html"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/aws/lambda/create-athena-partition"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/assets"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/assets/projects/crest"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/assets/projects/fallbacks"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/assets/projects/fonts"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/assets/projects/icons"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/assets/projects/marque"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/assets/projects/meta-icons"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/assets/projects/model-signatures"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/assets/projects/styles"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/component-meta"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/components"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "imask"
        versions: [ ">=2" ]
      - dependency-name: "change-case"
        versions: [ ">=5" ]
      - dependency-name: "@types/react"
        versions: [ ">18.2.65" ]

  - package-ecosystem: "npm"
    directory: "/packages/components-angular"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "globby"
        versions: [ ">=12" ]

  - package-ecosystem: "npm"
    directory: "/packages/components-angular/projects/angular-wrapper"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/components-js"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "@playwright/test"
        versions: [ "1.43", "1.44" ]

  - package-ecosystem: "npm"
    directory: "/packages/components-js/projects/components-manager-cli"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "globby"
        versions: [ ">=12" ]

  - package-ecosystem: "npm"
    directory: "/packages/components-js/projects/components-manager-core"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/components-js/projects/components-wrapper"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/components-js/projects/jsdom-polyfill"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/components-js/projects/partials"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/components-react"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "styled-components"
        versions: [ ">=6" ]
      - dependency-name: "@types/react"
        versions: [ ">18.2.65" ]

  - package-ecosystem: "npm"
    directory: "/packages/components-react/projects/nextjs"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "@types/react"
        versions: [ ">18.2.65" ]

  - package-ecosystem: "npm"
    directory: "/packages/components-react/projects/react-ssr-wrapper"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/components-react/projects/react-wrapper"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/components-react/projects/remix"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/components-react/projects/uxpin-wrapper"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "@types/react"
        versions: [ ">18.2.65" ]

  - package-ecosystem: "npm"
    directory: "/packages/components-vue"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/components-vue/projects/vue-wrapper"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/crawler"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "@playwright/test"
        versions: [ "1.43", "1.44" ]

  - package-ecosystem: "npm"
    directory: "/packages/storefront"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "@playwright/test"
        versions: [ "1.43", "1.44" ]
      - dependency-name: "vue"
        versions: [ ">=3" ]
      - dependency-name: "vue-router"
        versions: [ ">=4" ]
      - dependency-name: "vue-template-compiler"
        versions: [ ">=3" ]
      - dependency-name: "vuex"
        versions: [ ">=4" ]
      - dependency-name: "@vue/*"
        versions: [ ">=5" ]
      - dependency-name: "sass-loader"
        versions: [ ">=11" ]
      - dependency-name: "vmark*"
        versions: [ ">=2" ]
      - dependency-name: "@stackblitz/sdk"
        versions: [ ">=2" ]
      - dependency-name: "imask"
        versions: [ ">=2" ]
      - dependency-name: "change-case"
        versions: [ ">=5" ]

  - package-ecosystem: "npm"
    directory: "/packages/utilities"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "styled-components"
        versions: [ ">=6" ]
      - dependency-name: "@types/react"
        versions: [ ">18.2.65" ]

  - package-ecosystem: "npm"
    directory: "/packages/utilities/projects/utilities"
    schedule:
      interval: "monthly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "styled-components"
        versions: [ ">=6" ]
