on:
  pull_request:
    branches:
      - main
name: 'External Contribution'
jobs:
  build-and-test:
    name: 'Build and Test'
    if: ${{ github.event_name == 'push' && github.event.pull_request.head.repo.full_name != 'porsche-design-system/porsche-design-system' }}
    uses: ./.github/workflows/build-and-test.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

